-- 알림함: 개별 알림 항목(중복 방지·읽음)과 공지.
-- 새로 올라온 물건만 알림하기 위해 매칭 결과를 항목 단위로 저장한다(PK: user_id+item_key).
-- 백엔드 배포 워크플로는 prisma migrate를 실행하지 않으므로, 이 파일을 Supabase에 직접 적용한다.
--   psql "$DATABASE_URL" -f backend/prisma/manual/notification-inbox.sql

CREATE TABLE IF NOT EXISTS public.notification_item (
  user_id        text NOT NULL REFERENCES public."user"(id) ON DELETE CASCADE,
  item_key       text NOT NULL,          -- auction:<docid> | onbid:<...> | notice:<id>
  kind           text NOT NULL,          -- auction | onbid | notice
  origin         text NOT NULL,          -- favorite | condition | notice
  condition_name text,
  event_date     date,
  title          text,
  detail         text,
  read_at        timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, item_key)
);
CREATE INDEX IF NOT EXISTS notification_item_user_idx ON public.notification_item(user_id, read_at, event_date);

-- 운영 공지. active=true인 공지가 모든 회원 알림함에 1회 노출된다.
CREATE TABLE IF NOT EXISTS public.notice (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        text NOT NULL,
  body         text,
  link         text,
  published_at timestamptz NOT NULL DEFAULT now(),
  active       boolean NOT NULL DEFAULT true
);

ALTER TABLE public.notification_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notice ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN
    REVOKE ALL ON public.notification_item FROM anon;
    REVOKE ALL ON public.notice FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN
    REVOKE ALL ON public.notification_item FROM authenticated;
    REVOKE ALL ON public.notice FROM authenticated;
  END IF;
END $$;
