-- 회원 행동 로그(탐색·필터·찜·AI질문 등). append-only.
-- 백엔드 배포 워크플로는 prisma migrate를 실행하지 않으므로, 이 파일을 Supabase에 직접 적용한다.
--   psql "$DATABASE_URL" -f backend/prisma/manual/user-event.sql

CREATE TABLE IF NOT EXISTS public.user_event (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     text NOT NULL REFERENCES public."user"(id) ON DELETE CASCADE,
  type        text NOT NULL,
  entity_id   text,
  payload     jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS user_event_user_idx ON public.user_event(user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS user_event_type_idx ON public.user_event(type, occurred_at DESC);

ALTER TABLE public.user_event ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN
    REVOKE ALL ON public.user_event FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN
    REVOKE ALL ON public.user_event FROM authenticated;
  END IF;
END $$;
