<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.sitemaps.org/schemas/sitemap/0.9"
           xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
           elementFormDefault="qualified">
  <xs:element name="urlset">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="url" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="url">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="loc"/>
        <xs:element ref="lastmod" minOccurs="0"/>
        <xs:element ref="changefreq" minOccurs="0"/>
        <xs:element ref="priority" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="loc" type="xs:anyURI"/>
  <xs:element name="lastmod" type="xs:string"/>

  <xs:element name="changefreq">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="always"/>
        <xs:enumeration value="hourly"/>
        <xs:enumeration value="daily"/>
        <xs:enumeration value="weekly"/>
        <xs:enumeration value="monthly"/>
        <xs:enumeration value="yearly"/>
        <xs:enumeration value="never"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="priority">
    <xs:simpleType>
      <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0.0"/>
        <xs:maxInclusive value="1.0"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>