-- BuildingInfo 테이블 데이터 임포트
-- 파일 경로 및 인코딩 주의: PostgresSQL 서버에서 접근 가능한 절대 경로 또는 상대 경로를 사용해야 합니다.
-- CSV 파일이 큰 경우 COPY 명령어가 가장 효율적입니다.

COPY BuildingInfo (
    PLAT_PLC, SGG_CD_NM, STDG_CD_NM, PLOT_SE_CD_NM, MN_LOTNO, SUB_LOTNO, SPAREA_NM, BLCK_NO, LT_NO,
    NA_ROAD_CD_NM, NA_STDG_CD_NM, NA_GUGSE_CD_NM, NA_MN_LOTNO, NA_SUB_LOTNO, BDRG_SN, LDGR_SE_CD_NM,
    LDGR_KIND_CD_NM, DNG_NM, MANX_SE_CD_NM, SIAR, BDAR, BDCVRT, GFA, FART_CMPTTN_GFA, FART,
    STRCT_CD_NM, ETC_STRCT_INFO, MN_USG_CD_NM, ETC_USG_CN, ROOF_CD_NM, ETC_ROOF_NM, HH_CNT, FML_CNT,
    HO_CNT, GRND_NOFL, UDGD_NOFL, HG, PSNGR_ELVTR_CNT, EUSE_ELVTR_CNT, ANX_BDST_CNT, ANX_BDST_AREA,
    TOL_DNG_GFA, INDR_MCNCL_CNTOM, INDR_MCNCL_AREA, OTDR_MCNCL_CNTOM, OTDR_MCNCL_AREA, INDR_SFPRPL_CNTOM,
    INDR_SFPRPL_AREA, OTDR_SFPRPL_CNTOM, OTDR_SFPRPL_AREA, PRMSN_YMD, BGNCST_YMD, USE_APRV_YMD,
    ENRG_EFCY_GRD_VL, ENRG_RTRDT, EPI_SCR, ECFRD_BDST_GRD_VL, ECFRD_BDST_CERT_SCR, INTG_BDST_GRD_VL,
    INTG_BDST_CERT_SCR, RSER_DESIGN_APLCN_YN, RSER_ABLT_CN
)
FROM '/var/lib/postgresql/data/서울시 건축물대장 표제부 utf-8.csv'
WITH (
    FORMAT CSV,
    HEADER,
    ENCODING 'UTF8',
    QUOTE '"',
    DELIMITER ',',
    NULL ''
);

-- BuildingFloor 테이블 데이터 임포트
COPY BuildingFloor (
    PLAT_PLC, SGG_CD_NM, STDG_CD_NM, PLOT_SE_CD_NM, MN_LOTNO, SUB_LOTNO, SPAREA_NM, BLCK_NO, LT_NO,
    NA_ROAD_CD_NM, NA_STDG_CD_NM, NA_GUGSE_CD_NM, NA_MN_LOTNO, NA_SUB_LOTNO, FLR_CB_OLN_SN, BDRG_SN,
    FLR_SE_CD_NM, FLR_NO, FLR_NO_NM, STRCT_CD_NM, ETC_STRCT_INFO, MN_USG_CD_NM, ETC_USG_CN, AREA,
    MANX_SE_CD_NM, AREA_EXCL_YN
)
FROM '/var/lib/postgresql/data/서울시 건축물대장 층별개요.csv'
WITH (
    FORMAT CSV,
    HEADER,
    ENCODING 'UTF8',
    QUOTE '"',
    DELIMITER ',',
    NULL ''
);
