-- 05-optimized-import.sql (Deprecated. Use 06-full-import-optimized.sql for integrated high-speed migration)
CREATE UNLOGGED TABLE staging_building_info (
    PLAT_PLC TEXT, SGG_CD_NM TEXT, STDG_CD_NM TEXT, PLOT_SE_CD_NM TEXT, MN_LOTNO TEXT, SUB_LOTNO TEXT, SPAREA_NM TEXT, BLCK_NO TEXT, LT_NO TEXT,
    NA_ROAD_CD_NM TEXT, NA_STDG_CD_NM TEXT, NA_GUGSE_CD_NM TEXT, NA_MN_LOTNO TEXT, NA_SUB_LOTNO TEXT, BDRG_SN TEXT, LDGR_SE_CD_NM TEXT,
    LDGR_KIND_CD_NM TEXT, DNG_NM TEXT, MANX_SE_CD_NM TEXT, SIAR TEXT, BDAR TEXT, BDCVRT TEXT, GFA TEXT, FART_CMPTTN_GFA TEXT, FART TEXT,
    STRCT_CD_NM TEXT, ETC_STRCT_INFO TEXT, MN_USG_CD_NM TEXT, ETC_USG_CN TEXT, ROOF_CD_NM TEXT, ETC_ROOF_NM TEXT, HH_CNT TEXT, FML_CNT TEXT,
    HO_CNT TEXT, GRND_NOFL TEXT, UDGD_NOFL TEXT, HG TEXT, PSNGR_ELVTR_CNT TEXT, EUSE_ELVTR_CNT TEXT, ANX_BDST_CNT TEXT, ANX_BDST_AREA TEXT,
    TOL_DNG_GFA TEXT, INDR_MCNCL_CNTOM TEXT, INDR_MCNCL_AREA TEXT, OTDR_MCNCL_CNTOM TEXT, OTDR_MCNCL_AREA TEXT, INDR_SFPRPL_CNTOM TEXT,
    INDR_SFPRPL_AREA TEXT, OTDR_SFPRPL_CNTOM TEXT, OTDR_SFPRPL_AREA TEXT, PRMSN_YMD TEXT, BGNCST_YMD TEXT, USE_APRV_YMD TEXT,
    ENRG_EFCY_GRD_VL TEXT, ENRG_RTRDT TEXT, EPI_SCR TEXT, ECFRD_BDST_GRD_VL TEXT, ECFRD_BDST_CERT_SCR TEXT, INTG_BDST_GRD_VL TEXT,
    INTG_BDST_CERT_SCR TEXT, RSER_DESIGN_APLCN_YN TEXT, RSER_ABLT_CN TEXT
);

DROP TABLE IF EXISTS staging_building_floor;
CREATE UNLOGGED TABLE staging_building_floor (
    PLAT_PLC TEXT, SGG_CD_NM TEXT, STDG_CD_NM TEXT, PLOT_SE_CD_NM TEXT, MN_LOTNO TEXT, SUB_LOTNO TEXT, SPAREA_NM TEXT, BLCK_NO TEXT, LT_NO TEXT,
    NA_ROAD_CD_NM TEXT, NA_STDG_CD_NM TEXT, NA_GUGSE_CD_NM TEXT, NA_MN_LOTNO TEXT, NA_SUB_LOTNO TEXT, FLR_CB_OLN_SN TEXT, BDRG_SN TEXT,
    FLR_SE_CD_NM TEXT, FLR_NO TEXT, FLR_NO_NM TEXT, STRCT_CD_NM TEXT, ETC_STRCT_INFO TEXT, MN_USG_CD_NM TEXT, ETC_USG_CN TEXT, AREA TEXT,
    MANX_SE_CD_NM TEXT, AREA_EXCL_YN TEXT
);

-- 2. 고속 벌크 로드 (\copy 명령용 템플릿)
-- 이 부분은 psql 클라이언트에서 실행되어야 하므로 SQL 파일에는 주석으로만 남깁니다.
-- \copy staging_building_info FROM 'database/staging_building_info.csv' WITH (FORMAT CSV, HEADER, ENCODING 'UTF8', NULL '');
-- \copy staging_building_floor FROM 'database/staging_building_floor.csv' WITH (FORMAT CSV, HEADER, ENCODING 'UTF8', NULL '');

-- 3. 데이터 변환 및 운영 테이블 이관 로직 (함수로 정의하거나 직접 실행)
-- 성능을 위해 외래키 제약 조건을 일시적으로 비활성화하는 것을 권장하지만, 
-- 여기서는 데이터 무결성을 위해 ON CONFLICT를 활용한 고속 삽입을 수행합니다.

-- building_info 이관
INSERT INTO building_info (
    PLAT_PLC, SGG_CD_NM, STDG_CD_NM, PLOT_SE_CD_NM, MN_LOTNO, SUB_LOTNO, SPAREA_NM, BLCK_NO, LT_NO,
    NA_ROAD_CD_NM, NA_STDG_CD_NM, NA_GUGSE_CD_NM, NA_MN_LOTNO, NA_SUB_LOTNO, BDRG_SN, LDGR_SE_CD_NM,
    LDGR_KIND_CD_NM, DNG_NM, MANX_SE_CD_NM, SIAR, BDAR, BDCVRT, GFA, FART_CMPTTN_GFA, FART,
    STRCT_CD_NM, ETC_STRCT_INFO, MN_USG_CD_NM, ETC_USG_CN, ROOF_CD_NM, ETC_ROOF_NM, HH_CNT, FML_CNT,
    HO_CNT, GRND_NOFL, UDGD_NOFL, HG, PSNGR_ELVTR_CNT, EUSE_ELVTR_CNT, ANX_BDST_CNT, ANX_BDST_AREA,
    TOL_DNG_GFA, INDR_MCNCL_CNTOM, INDR_MCNCL_AREA, OTDR_MCNCL_CNTOM, OTDR_MCNCL_AREA, INDR_SFPRPL_CNTOM,
    INDR_SFPRPL_AREA, OTDR_SFPRPL_CNTOM, OTDR_SFPRPL_AREA, PRMSN_YMD, BGNCST_YMD, USE_APRV_YMD,
    ENRG_EFCY_GRD_VL, ENRG_RTRDT, EPI_SCR, ECFRD_BDST_GRD_VL, ECFRD_BDST_CERT_SCR, INTG_BDST_GRD_VL,
    INTG_BDST_CERT_SCR, RSER_DESIGN_APLCN_YN, RSER_ABLT_CN
)
SELECT 
    PLAT_PLC, SGG_CD_NM, STDG_CD_NM, PLOT_SE_CD_NM, MN_LOTNO, SUB_LOTNO, SPAREA_NM, BLCK_NO, LT_NO,
    NA_ROAD_CD_NM, NA_STDG_CD_NM, NA_GUGSE_CD_NM, NULLIF(NA_MN_LOTNO, '')::INTEGER, NULLIF(NA_SUB_LOTNO, '')::INTEGER, BDRG_SN, LDGR_SE_CD_NM,
    LDGR_KIND_CD_NM, DNG_NM, MANX_SE_CD_NM, NULLIF(SIAR, '')::NUMERIC, NULLIF(BDAR, '')::NUMERIC, NULLIF(BDCVRT, '')::NUMERIC, NULLIF(GFA, '')::NUMERIC, NULLIF(FART_CMPTTN_GFA, '')::NUMERIC, NULLIF(FART, '')::NUMERIC,
    STRCT_CD_NM, ETC_STRCT_INFO, MN_USG_CD_NM, ETC_USG_CN, ROOF_CD_NM, ETC_ROOF_NM, NULLIF(HH_CNT, '')::INTEGER, NULLIF(FML_CNT, '')::INTEGER,
    NULLIF(HO_CNT, '')::INTEGER, NULLIF(GRND_NOFL, '')::INTEGER, NULLIF(UDGD_NOFL, '')::INTEGER, NULLIF(HG, '')::NUMERIC, NULLIF(PSNGR_ELVTR_CNT, '')::INTEGER, NULLIF(EUSE_ELVTR_CNT, '')::INTEGER, NULLIF(ANX_BDST_CNT, '')::INTEGER, NULLIF(ANX_BDST_AREA, '')::NUMERIC,
    NULLIF(TOL_DNG_GFA, '')::NUMERIC, NULLIF(INDR_MCNCL_CNTOM, '')::INTEGER, NULLIF(INDR_MCNCL_AREA, '')::NUMERIC, NULLIF(OTDR_MCNCL_CNTOM, '')::INTEGER, NULLIF(OTDR_MCNCL_AREA, '')::NUMERIC, NULLIF(INDR_SFPRPL_CNTOM, '')::INTEGER,
    NULLIF(INDR_SFPRPL_AREA, '')::NUMERIC, NULLIF(OTDR_SFPRPL_CNTOM, '')::INTEGER, NULLIF(OTDR_SFPRPL_AREA, '')::NUMERIC, 
    CASE WHEN PRMSN_YMD ~ '^\d{8}$' THEN TO_DATE(PRMSN_YMD, 'YYYYMMDD') ELSE NULL END,
    CASE WHEN BGNCST_YMD ~ '^\d{8}$' THEN TO_DATE(BGNCST_YMD, 'YYYYMMDD') ELSE NULL END,
    CASE WHEN USE_APRV_YMD ~ '^\d{8}$' THEN TO_DATE(USE_APRV_YMD, 'YYYYMMDD') ELSE NULL END,
    ENRG_EFCY_GRD_VL, NULLIF(ENRG_RTRDT, '')::NUMERIC, NULLIF(EPI_SCR, '')::NUMERIC, ECFRD_BDST_GRD_VL, NULLIF(ECFRD_BDST_CERT_SCR, '')::INTEGER, INTG_BDST_GRD_VL,
    NULLIF(INTG_BDST_CERT_SCR, '')::INTEGER, LEFT(RSER_DESIGN_APLCN_YN, 1), RSER_ABLT_CN
FROM staging_building_info
ON CONFLICT (PLAT_PLC) DO UPDATE SET
    SGG_CD_NM = EXCLUDED.SGG_CD_NM, STDG_CD_NM = EXCLUDED.STDG_CD_NM, GFA = EXCLUDED.GFA, USE_APRV_YMD = EXCLUDED.USE_APRV_YMD;

-- building_floor 이관
INSERT INTO building_floor (
    FLR_CB_OLN_SN, PLAT_PLC, SGG_CD_NM, STDG_CD_NM, PLOT_SE_CD_NM, MN_LOTNO, SUB_LOTNO, SPAREA_NM, BLCK_NO, LT_NO,
    NA_ROAD_CD_NM, NA_STDG_CD_NM, NA_GUGSE_CD_NM, NA_MN_LOTNO, NA_SUB_LOTNO, BDRG_SN,
    FLR_SE_CD_NM, FLR_NO, FLR_NO_NM, STRCT_CD_NM, ETC_STRCT_INFO, MN_USG_CD_NM, ETC_USG_CN, AREA,
    MANX_SE_CD_NM, AREA_EXCL_YN
)
SELECT 
    FLR_CB_OLN_SN, PLAT_PLC, SGG_CD_NM, STDG_CD_NM, PLOT_SE_CD_NM, MN_LOTNO, SUB_LOTNO, SPAREA_NM, BLCK_NO, LT_NO,
    NA_ROAD_CD_NM, NA_STDG_CD_NM, NA_GUGSE_CD_NM, NULLIF(NA_MN_LOTNO, '')::INTEGER, NULLIF(NA_SUB_LOTNO, '')::INTEGER, BDRG_SN,
    FLR_SE_CD_NM, NULLIF(FLR_NO, '')::INTEGER, FLR_NO_NM, STRCT_CD_NM, ETC_STRCT_INFO, MN_USG_CD_NM, ETC_USG_CN, NULLIF(AREA, '')::NUMERIC,
    MANX_SE_CD_NM, LEFT(AREA_EXCL_YN, 1)
FROM staging_building_floor
ON CONFLICT (FLR_CB_OLN_SN) DO UPDATE SET
    AREA = EXCLUDED.AREA, FLR_NO = EXCLUDED.FLR_NO;

-- 4. 스테이징 테이블 삭제
DROP TABLE IF EXISTS staging_building_info;
DROP TABLE IF EXISTS staging_building_floor;

-- 5. 통계 정보 업데이트
ANALYZE building_info;
ANALYZE building_floor;
